---

# Check the Architecture of OS
# - name: Must be 64-bit
#   fail:
#     msg: "This role is intended for use only 64-bit"
#   when: (ansible_architecture != 'x86_64')

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks:  '{{ ansible_os_family }}.yml'

# Config tasks.
- include_tasks:  'config.yml'