---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks:  '{{ ansible_os_family }}.yml'

# Config tasks.
- include_tasks:  'config.yml'